import Head from "next/head"
import Link from "next/link"
import { Footer } from "~/components/Footer"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <nav></nav>
      <main></main>
      <footer>
        <Footer />
      </footer>
    </>
  )
}
